import type { FormData, DifficultyLevel } from '@/types';
import { makeInferences } from './inferences';

export function generatePrompt(formData: FormData): string {
  const inferences = makeInferences(formData);
  const difficulty = formData.difficulty;

  let prompt = `# ROLE
You are an elite full-stack developer and product architect with deep expertise in modern web development, UI/UX design, and creating production-ready applications.

`;

  prompt += generateProjectOverview(formData);
  prompt += generateBranding(formData);
  prompt += generateProductScope(formData, inferences);
  prompt += generateCoreFeatures(formData);
  prompt += generateBackendInfrastructure(formData, inferences);
  prompt += generatePagesAndNavigation(formData);
  prompt += generateDesignPreferences(formData);
  prompt += generateTechnicalStack(formData, inferences);
  prompt += generateAdditionalContext(formData);
  prompt += generateUiUxGuidelines(formData, difficulty);
  prompt += generateDevelopmentRequirements(formData, difficulty);
  prompt += generateDeliverables(formData, difficulty);

  prompt += `\n---
Generated by Architect Prime V3 (AP3)
Difficulty Level: ${formData.difficulty.charAt(0).toUpperCase() + formData.difficulty.slice(1)}
`;

  return prompt;
}

function generateProjectOverview(formData: FormData): string {
  return `# PROJECT OVERVIEW
## Product Identity
- **Name**: ${formData.appName}
- **Tagline**: ${formData.tagline}
- **Elevator Pitch**: ${formData.elevatorPitch}

## Problem & Solution
- **Problem Solved**: ${formData.problemSolved}
- **Competitive Advantage**: ${formData.competitiveAdvantage}

## Target Audience
${formData.targetAudience}

${formData.competitors ? `## Competitors
${formData.competitors}
` : ''}
`;
}

function generateBranding(formData: FormData): string {
  const accentColors = formData.accentColors.length > 0 
    ? formData.accentColors.map((c, i) => `- Accent ${i + 1}: ${c}`).join('\n')
    : 'None specified';

  return `# BRANDING & AESTHETIC
## Color Palette
- **Primary**: ${formData.primaryColor}
${accentColors}

## Design Vibe
${formData.designVibe.join(', ')}

## Typography
${formData.typography}

## Brand Voice
${formData.brandVoice}

## Visual Style
${formData.backgroundStyle}

${formData.logoAssets ? `## Brand Assets
${formData.logoAssets}
` : ''}
`;
}

function generateProductScope(formData: FormData, inferences: any): string {
  return `# PRODUCT SCOPE
## Category
${formData.category.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}

## Authentication & Security
${inferences.auth}
- Team Structure: ${formData.teamStructure.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}

## Scalability
- Expected Scale: ${formData.scalability.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}
${formData.expectedGrowth ? `- Expected Growth: ${formData.expectedGrowth}` : ''}
`;
}

function generateCoreFeatures(formData: FormData): string {
  let section = `# CORE FEATURES
## Primary Features
${formData.primaryFeatures}

${formData.secondaryFeatures ? `## Secondary Features
${formData.secondaryFeatures}
` : ''}

## User Journeys
${formData.userFlows}

## Monetization
- Model: ${formData.monetization.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}
${formData.pricingTiers ? `- Pricing Tiers:
${formData.pricingTiers}` : ''}
${formData.featurePriority ? `- Feature Priority: ${formData.featurePriority}` : ''}
`;

  return section;
}

function generateBackendInfrastructure(formData: FormData, inferences: any): string {
  let section = `# BACKEND INFRASTRUCTURE
## Data Storage
${inferences.database}
${formData.userDataStorage ? `- Data Retention: ${formData.dataRetention || 'Not specified'}` : ''}
`;

  if (formData.fileUploads && formData.fileUploads.length > 0) {
    section += `## File Uploads
- Upload Types: ${formData.fileUploads.join(', ')}
- Storage Solution: ${inferences.storage}
`;
  }

  if (formData.realtimeFeatures && formData.realtimeFeatures.length > 0) {
    section += `## Real-time Features
- Features: ${formData.realtimeFeatures.join(', ')}
- Solution: ${inferences.realtime}
`;
  }

  if (formData.calendarIntegration) {
    section += `## Calendar Integration
${inferences.calendar}
`;
  }

  if (formData.paymentIntegration) {
    section += `## Payments
${inferences.payments}
`;
  }

  if (formData.emailNotifications && formData.emailNotifications.length > 0) {
    section += `## Email & Notifications
- Types: ${formData.emailNotifications.join(', ')}
- Service: ${inferences.email}
`;
  }

  if (formData.externalApis) {
    section += `## External APIs
${formData.externalApis}
`;
  }

  if (formData.apiRateLimiting) {
    section += `## API Requirements
- Rate Limiting: ${formData.apiRateLimiting}
`;
  }

  if (formData.securityRequirements && formData.securityRequirements.length > 0) {
    section += `## Security & Compliance
${formData.securityRequirements.map(req => `- ${req.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}`).join('\n')}
`;
  }

  return section;
}

function generatePagesAndNavigation(formData: FormData): string {
  let section = `# PAGES & NAVIGATION
## Must-Have Pages
${formData.mustHavePages}

## Navigation Structure
${formData.navigationStructure.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}

## Hero Section
- Headline: ${formData.heroHeadline}
${formData.heroSubheadline ? `- Subheadline: ${formData.heroSubheadline}` : ''}
${formData.heroCta ? `- CTA: ${formData.heroCta}` : ''}
- Visual Style: ${formData.heroImageStyle.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}

`;

  if (formData.keyUiComponents && formData.keyUiComponents.length > 0) {
    section += `## Key UI Components
${formData.keyUiComponents.map(c => `- ${c.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}`).join('\n')}
`;
  }

  if (formData.seoRequirements && formData.seoRequirements.length > 0) {
    section += `## SEO Requirements
${formData.seoRequirements.map(req => `- ${req.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}`).join('\n')}
`;
  }

  if (formData.socialMediaIntegration && formData.socialMediaIntegration.length > 0) {
    section += `## Social Media Integration
${formData.socialMediaIntegration.map(s => `- ${s.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}`).join('\n')}
`;
  }

  return section;
}

function generateDesignPreferences(formData: FormData): string {
  let section = `# DESIGN PREFERENCES
${formData.inspirations ? `## Inspirations
${formData.inspirations}

` : ''}## Mobile Strategy
${formData.mobileDesktop.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}

`;

  if (formData.animationPreferences && formData.animationPreferences.length > 0) {
    section += `## Animations
${formData.animationPreferences.map(anim => `- ${anim.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}`).join('\n')}
`;
  }

  section += `## Loading States
${formData.loadingPreference.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}

`;

  if (formData.accessibilityRequirements && formData.accessibilityRequirements.length > 0) {
    section += `## Accessibility
${formData.accessibilityRequirements.map(acc => `- ${acc.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}`).join('\n')}
`;
  }

  if (formData.performanceGoals && formData.performanceGoals.length > 0) {
    section += `## Performance Goals
${formData.performanceGoals.map(goal => `- ${goal.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}`).join('\n')}
`;
  }

  if (formData.imageOptimization && formData.imageOptimization.length > 0) {
    section += `## Image Optimization
${formData.imageOptimization.map(opt => `- ${opt.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}`).join('\n')}
`;
  }

  return section;
}

function generateTechnicalStack(formData: FormData, inferences: any): string {
  let section = `# TECHNICAL STACK
## Core Stack
- **Framework**: Next.js 15 (App Router)
- **Language**: TypeScript
- **Styling**: Tailwind CSS v4
- **Components**: shadcn/ui

`;

  if (formData.additionalTechPreferences) {
    section += `## Additional Technologies
${formData.additionalTechPreferences}
`;
  }

  if (formData.avoidTech) {
    section += `## Technologies to Avoid
${formData.avoidTech}
`;
  }

  section += `## Database
${formData.databasePreference || inferences.database}

`;

  if (formData.cms) {
    section += `## CMS
${formData.cms}
`;
  }

  section += `## Deployment
${formData.deploymentTarget.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}

`;

  if (formData.cicdRequirements && formData.cicdRequirements.length > 0) {
    section += `## CI/CD
${formData.cicdRequirements.map(cicd => `- ${cicd.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}`).join('\n')}
`;
  }

  if (formData.environmentVariables) {
    section += `## Environment Variables
${formData.environmentVariables}
`;
  }

  if (formData.testingStrategy && formData.testingStrategy.length > 0) {
    section += `## Testing
${formData.testingStrategy.map(test => `- ${test.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}`).join('\n')}
`;
  }

  if (formData.errorTracking) {
    section += `## Error Tracking
${formData.errorTracking}
`;
  }

  if (formData.analyticsIntegration) {
    section += `## Analytics
${formData.analyticsIntegration}
`;
  }

  return section;
}

function generateAdditionalContext(formData: FormData): string {
  let section = `# ADDITIONAL CONTEXT
`;

  const hasContent = 
    formData.existingRepo ||
    formData.technicalConstraints ||
    formData.thirdPartyLibraries ||
    formData.knownLimitations ||
    formData.successMetrics ||
    formData.teamSize ||
    formData.budgetConstraints ||
    formData.timeline ||
    formData.maintenance;

  if (!hasContent) {
    section += `No additional context provided.
`;
    return section;
  }

  if (formData.existingRepo) {
    section += `## Existing Code
${formData.existingRepo}
`;
  }

  if (formData.technicalConstraints) {
    section += `## Technical Constraints
${formData.technicalConstraints}
`;
  }

  if (formData.thirdPartyLibraries) {
    section += `## Third-Party Libraries
${formData.thirdPartyLibraries}
`;
  }

  if (formData.knownLimitations) {
    section += `## Known Limitations
${formData.knownLimitations}
`;
  }

  if (formData.successMetrics) {
    section += `## Success Metrics
${formData.successMetrics}
`;
  }

  if (formData.teamSize) {
    section += `## Team
- Size: ${formData.teamSize}
`;
  }

  if (formData.budgetConstraints) {
    section += `## Budget
${formData.budgetConstraints}
`;
  }

  if (formData.timeline) {
    section += `## Timeline
${formData.timeline}
`;
  }

  if (formData.maintenance) {
    section += `## Maintenance
${formData.maintenance}
`;
  }

  return section;
}

function generateUiUxGuidelines(formData: FormData, difficulty: DifficultyLevel): string {
  return `# UI/UX GUIDELINES
## Design Principles
- Use modern 2025-2026 design trends
- Implement smooth 300-400ms animations (framer-motion)
- Apply glassmorphism tastefully
- Ensure WCAG AA accessibility compliance
- Responsive design (mobile-first approach)
- Dark mode by default with light mode toggle
- Clean, minimalist aesthetic with ${formData.primaryColor} brand color accents

## Visual Implementation
- Glassmorphism cards: \`backdrop-blur-xl bg-white/5 border-white/10\`
- Subtle grain texture on background
- Ambient floating particles
- Smooth page transitions
- Micro-interactions on hover/focus
- Dynamic focus rings with brand colors

## Component Guidelines
- Use shadcn/ui components as base
- Custom components should follow existing patterns
- Maintain consistent spacing (4px grid system)
- Use proper semantic HTML
- Implement proper loading states
${difficulty === 'advanced' || difficulty === 'expert' ? `- Add error boundaries for better error handling
- Implement skeleton screens for better perceived performance` : ''}
`;
}

function generateDevelopmentRequirements(formData: FormData, difficulty: DifficultyLevel): string {
  let section = `# DEVELOPMENT REQUIREMENTS
## Implementation Approach
- Server Components by default (where appropriate)
- Client Components only when interactivity needed
- Proper code splitting and lazy loading
- Optimize bundle size
${difficulty === 'advanced' || difficulty === 'expert' ? `- Implement error boundaries
- Add proper TypeScript strict mode
- Use proper error handling and logging` : ''}

## Security
- Environment variables for all secrets
- Proper input validation
- XSS/CSRF protection
- Secure authentication flows
- Rate limiting on API routes

## Performance Targets
- Lighthouse score: 95+
- First Contentful Paint: < 1s
- Time to Interactive: < 2s
- Largest Contentful Paint: < 2.5s
- Bundle size: < 200KB (gzipped)

## Accessibility
- ARIA labels on all interactive elements
- Keyboard navigation throughout
- Focus management in modals
- Screen reader compatible
- Proper color contrast (4.5:1 minimum)
- Reduced motion support
`;

  return section;
}

function generateDeliverables(formData: FormData, difficulty: DifficultyLevel): string {
  let section = `# DELIVERABLES
Build the complete production-ready application with:
1. Clean, maintainable code structure
2. Proper environment variables configuration
3. Comprehensive README with setup instructions
4. Optimized performance (lazy loading, code splitting)
5. Production-ready authentication
6. Database schema with proper relationships
7. API routes for all required functionality
8. Error handling and edge cases
9. Loading states and skeletons
10. Full accessibility compliance
11. SEO optimization
12. Analytics tracking
${difficulty === 'advanced' || difficulty === 'expert' ? `13. Error monitoring setup
14. Comprehensive test coverage
15. CI/CD pipeline configuration` : ''}

Start with project setup, then implement routing, components, business logic, testing, and finally deployment. Ensure all features work end-to-end.
`;

  return section;
}
