import type { Template, FormData } from '@/types';

export const templates: Template[] = [
  {
    id: 'saas-mvp',
    name: 'SaaS MVP',
    description: 'Fast-track your SaaS product with essential features, authentication, and subscription billing',
    category: 'web-app-saas',
    icon: 'rocket',
    prefillData: {
      category: 'web-app-saas',
      authType: 'email-password',
      authProvider: 'clerk',
      teamStructure: 'multi-user-shared',
      scalability: 'beta',
      monetization: 'freemium',
      designVibe: ['modern-minimal'],
      typography: 'inter',
      brandVoice: 'professional',
      mobileDesktop: 'mobile-first',
      loadingPreference: 'skeletons',
      accessibilityRequirements: ['wcag-aa', 'keyboard-nav'],
      performanceGoals: ['instant', 'lighthouse-95'],
      deploymentTarget: 'vercel',
      keyUiComponents: ['dark-mode-toggle', 'user-settings'],
      animationPreferences: ['micro-interactions', 'page-transitions'],
      imageOptimization: ['next-image', 'lazy-load', 'webp'],
      seoRequirements: ['meta-tags', 'sitemap', 'og-tags'],
    } as Partial<FormData>,
  },
  {
    id: 'ecommerce',
    name: 'E-commerce Store',
    description: 'Complete online store with product catalog, cart, checkout, and payment processing',
    category: 'ecommerce',
    icon: 'shopping-cart',
    prefillData: {
      category: 'ecommerce',
      authType: 'email-password',
      authProvider: 'supabase',
      teamStructure: 'multi-user-shared',
      scalability: 'production',
      monetization: 'subscription',
      designVibe: ['corporate-professional'],
      typography: 'inter',
      brandVoice: 'professional',
      mobileDesktop: 'mobile-first',
      loadingPreference: 'skeletons',
      accessibilityRequirements: ['wcag-aa', 'keyboard-nav', 'screen-reader'],
      performanceGoals: ['lighthouse-95', 'fast-loading'],
      deploymentTarget: 'vercel',
      keyUiComponents: ['pricing-tables', 'testimonials', 'dark-mode-toggle'],
      animationPreferences: ['micro-interactions'],
      imageOptimization: ['next-image', 'lazy-load', 'webp', 'responsive'],
      seoRequirements: ['meta-tags', 'sitemap', 'structured-data', 'og-tags'],
      userDataStorage: true,
      fileUploads: ['product-images'],
      paymentIntegration: 'stripe',
      securityRequirements: ['gdpr', 'auth', 'encryption'],
    } as Partial<FormData>,
  },
  {
    id: 'landing-page',
    name: 'Landing Page',
    description: 'High-converting landing page with hero section, features, testimonials, and CTA',
    category: 'landing-page',
    icon: 'layout',
    prefillData: {
      category: 'landing-page',
      authType: 'none',
      teamStructure: 'single-user',
      scalability: 'mvp',
      monetization: 'free',
      designVibe: ['modern-minimal'],
      typography: 'geist',
      brandVoice: 'friendly',
      mobileDesktop: 'mobile-first',
      loadingPreference: 'progressive',
      accessibilityRequirements: ['wcag-aa', 'keyboard-nav'],
      performanceGoals: ['instant', 'lighthouse-95', 'seo-optimized'],
      deploymentTarget: 'vercel',
      keyUiComponents: ['feature-grids', 'testimonials', 'newsletter'],
      animationPreferences: ['micro-interactions', 'scroll-animations', 'hero-animations'],
      imageOptimization: ['next-image', 'lazy-load', 'webp'],
      seoRequirements: ['meta-tags', 'sitemap', 'structured-data', 'og-tags'],
      backgroundStyle: 'gradient',
    } as Partial<FormData>,
  },
  {
    id: 'dashboard',
    name: 'Internal Dashboard',
    description: 'Powerful internal tool for team collaboration, data visualization, and task management',
    category: 'dashboard',
    icon: 'bar-chart',
    prefillData: {
      category: 'dashboard',
      authType: 'email-password',
      authProvider: 'clerk',
      teamStructure: 'team-workspaces',
      scalability: 'beta',
      monetization: 'free',
      designVibe: ['corporate-professional'],
      typography: 'inter',
      brandVoice: 'professional',
      mobileDesktop: 'desktop-first',
      loadingPreference: 'skeletons',
      accessibilityRequirements: ['wcag-aa', 'keyboard-nav'],
      performanceGoals: ['instant'],
      deploymentTarget: 'vercel',
      keyUiComponents: ['dark-mode-toggle', 'user-settings', 'search'],
      animationPreferences: ['micro-interactions'],
      imageOptimization: ['next-image', 'lazy-load'],
      navigationStructure: 'sidebar',
      userDataStorage: true,
      realtimeFeatures: ['live-updates'],
      realtimeSolution: 'supabase-realtime',
      securityRequirements: ['auth', 'encryption'],
    } as Partial<FormData>,
  },
  {
    id: 'portfolio',
    name: 'Portfolio / Showcase',
    description: 'Beautiful portfolio to showcase your work, projects, and achievements',
    category: 'portfolio',
    icon: 'image',
    prefillData: {
      category: 'portfolio',
      authType: 'none',
      teamStructure: 'single-user',
      scalability: 'mvp',
      monetization: 'free',
      designVibe: ['modern-minimal'],
      typography: 'cabinet-grotesk',
      brandVoice: 'friendly',
      mobileDesktop: 'mobile-first',
      loadingPreference: 'progressive',
      accessibilityRequirements: ['wcag-aa', 'keyboard-nav'],
      performanceGoals: ['instant', 'lighthouse-95', 'seo-optimized'],
      deploymentTarget: 'vercel',
      keyUiComponents: ['feature-grids', 'testimonials'],
      animationPreferences: ['micro-interactions', 'scroll-animations'],
      imageOptimization: ['next-image', 'lazy-load', 'webp', 'responsive'],
      seoRequirements: ['meta-tags', 'sitemap', 'structured-data', 'og-tags'],
      socialMediaIntegration: ['twitter', 'linkedin', 'share-buttons'],
      backgroundStyle: 'gradient',
    } as Partial<FormData>,
  },
];

export function getTemplateById(id: string): Template | undefined {
  return templates.find((t) => t.id === id);
}

export function getTemplatesByCategory(category: FormData['category']): Template[] {
  return templates.filter((t) => t.category === category);
}
